### ISSUE TITLE
Сделана формула в векторном виде МХ401

### ISSUE THREAD

**Issue by JustSaintMike** [JustSaintMike/Point-around-Sun#1]
Угол меняется и считает, а вот расстояние постоянно, не понимаю как и куда его сделать переменной величиной

**Comment by justjune** [comment]
1. Выписать уравнения движения на бумажке, а не в Юнити.
2. Добавить в модель начальную скорость тела и начальное положение.
3. Если сделали расчет методм Р-К, то добавить еще одно тело через физику Юнити (для сравнения).
