### ISSUE TITLE
Добавлены уравнения для 3х тел 

### ISSUE THREAD

**Issue by JustSaintMike** [JustSaintMike/Point-around-Sun#2]
В мастере для 1 тела, то что было, а в бранче для 3х тел.

**Comment by JustSaintMike** [comment]
Михаил МХ401

**Comment by justjune** [comment]
То, что в "мастере" - не верно, потому что задано уравнение движения по окружности, что является крайне редко встречающимся случаем движения вокруг притягивающего центра.

**Comment by justjune** [comment]
То что во второй ветке - не верно, потому что ссылки на второе тело не получается.

**Comment by justjune** [comment]
Аналогичная ошибка и в третьей ветке.
